
CREATE ROLE TMBR_PRICING_SCRPT_ROLE;

GRANT SELECT ON THE.APPRAISAL_DATA_SUBMISSION TO TMBR_PRICING_SCRPT_ROLE;
GRANT SELECT ON THE.APPRAISAL_DATA_SUBMISSION_CTRL TO TMBR_PRICING_SCRPT_ROLE;
GRANT SELECT ON THE.ORG_UNIT TO TMBR_PRICING_SCRPT_ROLE;
GRANT SELECT ON THE.ADS_SUBMITTED_TIMBER_MARK TO TMBR_PRICING_SCRPT_ROLE;
GRANT SELECT ON THE.V_CLIENT_PUBLIC TO TMBR_PRICING_SCRPT_ROLE;
GRANT SELECT ON THE.RPF_LICENSEE_REP TO TMBR_PRICING_SCRPT_ROLE;
GRANT SELECT ON THE.ADS_BRIDGE TO TMBR_PRICING_SCRPT_ROLE;
GRANT SELECT ON THE.ADS_CULVERT TO TMBR_PRICING_SCRPT_ROLE;
GRANT SELECT ON THE.ADS_DETAILED_ENGINEERING_COST TO TMBR_PRICING_SCRPT_ROLE;
GRANT SELECT ON THE.ADS_TABULAR_ROAD_SECTION TO TMBR_PRICING_SCRPT_ROLE;
GRANT SELECT ON THE.ADS_SPECIFIED_OPERATION TO TMBR_PRICING_SCRPT_ROLE;

GRANT CONNECT TO TMBR_PRICING_SCRPT_ROLE;

GRANT TMBR_PRICING_SCRPT_ROLE TO TMBR_PRICING_SCRPT_PROXY;


CREATE USER TMBR_PRICING_SCRPT_PROXY
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE PROXY_ACCOUNT_DEFAULT
  ACCOUNT UNLOCK;

-- 1 Role for TMBR_PRICING_SCRPT_PROXY
GRANT TMBR_PRICING_SCRPT_ROLE TO TMBR_PRICING_SCRPT_PROXY;
ALTER USER TMBR_PRICING_SCRPT_PROXY DEFAULT ROLE ALL;

-- 1 System Privilege for TMBR_PRICING_SCRPT_PROXY
GRANT CREATE SESSION TO TMBR_PRICING_SCRPT_PROXY;
