
CREATE ROLE SCR_TMBRPRICING_ROLE;

GRANT SELECT ON THE.APPRAISAL_DATA_SUBMISSION TO SCR_TMBRPRICING_ROLE;
GRANT SELECT ON THE.APPRAISAL_DATA_SUBMISSION_CTRL TO SCR_TMBRPRICING_ROLE;
GRANT SELECT ON THE.ORG_UNIT TO SCR_TMBRPRICING_ROLE;
GRANT SELECT ON THE.ADS_SUBMITTED_TIMBER_MARK TO SCR_TMBRPRICING_ROLE;
GRANT SELECT ON THE.V_CLIENT_PUBLIC TO SCR_TMBRPRICING_ROLE;
GRANT SELECT ON THE.RPF_LICENSEE_REP TO SCR_TMBRPRICING_ROLE;
GRANT SELECT ON THE.ADS_BRIDGE TO SCR_TMBRPRICING_ROLE;
GRANT SELECT ON THE.ADS_CULVERT TO SCR_TMBRPRICING_ROLE;
GRANT SELECT ON THE.ADS_DETAILED_ENGINEERING_COST TO SCR_TMBRPRICING_ROLE;
GRANT SELECT ON THE.ADS_TABULAR_ROAD_SECTION TO SCR_TMBRPRICING_ROLE;
GRANT SELECT ON THE.ADS_SPECIFIED_OPERATION TO SCR_TMBRPRICING_ROLE;

CREATE USER PROXY_SCR_TMBRPRICING
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE USR01
  TEMPORARY TABLESPACE TEMP
  PROFILE PROXY_ACCOUNT_DEFAULT
  ACCOUNT UNLOCK;

-- 1 Role for TMBR_PRICING_SCRPT_PROXY
GRANT SCR_TMBRPRICING_ROLE TO PROXY_SCR_TMBRPRICING;
ALTER USER PROXY_SCR_TMBRPRICING DEFAULT ROLE ALL;

-- 1 System Privilege for TMBR_PRICING_SCRPT_PROXY
GRANT CREATE SESSION TO PROXY_SCR_TMBRPRICING;
